### ISSUE TITLE
Support for Xelatex/lualatex?

### ISSUE THREAD

**Issue by krishnakumarg1984** [tcassanelli/uni-bonn-thesis-template#1]
Can I use custom fonts through xelatex or lualatex?

Also, some showcase of math typography is appreciated.

**Comment by tcassanelli** [comment]
Yes you can change the font if you'd like, look at this answer in [TeX stackexchange](https://tex.stackexchange.com/questions/292727/how-to-change-the-font-style-of-elements-in-koma-script#292807) you can also look into the KOMA-Script manual. Be aware that if you change the font and specially the font size then the figures using the Python scripts won't match the style of the document anymore. To correct that you'll have to edit the [master_thesis_sty.mplstyle](https://github.com/tcassanelli/uni-bonn-thesis-template/blob/master/plot_scripts/master_thesis_sty.mplstyle) as well.

I can add some LaTeX math examples, but they are pretty standard and you can find them anywhere. Let me know if you have any problems or suggestions. Have a nice typing!

**Comment by krishnakumarg1984** [comment]
Thank you very much
